
services:
  mss-postgresql:
    image: postgres:17.2-bookworm
    container_name: mss-postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - ./docker/postgresql/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
      - ps-postgres-vol:/var/lib/postgresql/data
    networks:
      - ps-network

  mss-redis:
    image: redis:7.4.1-alpine
    container_name: mss-redis
    ports:
      - "6379:6379"
    env_file:
      - .env.local
    networks:
      - ps-network

networks:
  ps-network:
    driver: bridge

volumes:
  ps-postgres-vol:
