
services:
  mss-postgres:
    image: postgres:17.2-bookworm
    container_name: mss-postgres
    ports:
      - "5555:5432"
    env_file:
      - .env.local
    volumes:
      - ps-postgres-vol:/var/lib/postgresql/data
    networks:
      - ps-network

  mss-redis:
    image: redis:7.4.1-alpine
    container_name: mss-redis
    ports:
      - "6666:6379"
    env_file:
      - .env.local
    networks:
      - ps-network

networks:
  ps-network:
    driver: bridge

volumes:
  ps-postgres-vol:
