
server:
  port: 3001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: App-DB-Pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        useUnicode: true
        characterEncoding: UTF-8
        characterSetResults: UTF-8
        serverTimezone: UTC
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
