
server:
  http2:
    enabled: true
  port: 3000

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: admin
      password: admin
      database: mongo

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs.yaml
