
server:
  port: ${IDENTITY_PORT:6001}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${IDENTITY_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:admin}
#      database: 0
#      timeout: 5000

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.springframework.security: debug

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  duration-in-minutes: ${JWT_DURATION}
