
server:
  port: 3002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: App-DB-Pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        useUnicode: true
        characterEncoding: UTF-8
        characterSetResults: UTF-8
        serverTimezone: UTC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
#  data:
#    redis:
#      host: localhost
#      port: 6666
#      password: redis-admin
#      database: 0
#      timeout: 60000
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 8
#          max-wait: 10000
#          max-idle: 8
#          min-idle: 0

jwt:
  secret: abc123asdflasjdfklasdasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasddfaqwerqgsadzvasdrflaskdjfqoiweurqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerqwerasdfasdf

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.springframework.security: debug