server:
  http2:
    enabled: true

spring:
  threads.virtual.enabled: true
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: App-DB-Pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        useUnicode: true
        characterEncoding: UTF-8
        characterSetResults: UTF-8
        serverTimezone: UTC

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#  data:
#    redis:
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 50
#          max-wait: 0
#          max-idle: 50
#          min-idle: 25
